### PR TITLE
Update progit.asc

### PR DESCRIPTION
**Pull request by wbzyl**
Use callouts and admonitions icons instead of text in _progit.html_.

### CODE REVIEW

**Comment by wbzyl** [comment]
It works for me with these versions of gems:
```ruby
gem 'asciidoctor', '1.5.2'
gem 'asciidoctor-epub3', '1.5.0.alpha.4'
gem 'asciidoctor-pdf', '1.5.0.alpha.6'
```
--Włodek Bzyl

**Comment by ben** [comment]
Sorry for the delay. Can you paste a before-and-after screenshot for this change?

**Comment by aizulaiz** [comment]
Update

**Comment by jnavila** [comment]
Before:
image

After:
image

**Pull request merged**
