### PR TITLE
New line should separate sentences (corrections for all chapters)

### PR DESCRIPTION
**Pull request by noisy**
Like in my already merged previous [PR](https://github.com/progit/progit2/pull/329), this PR fixes missing new lines. With that changes all chapters will be consistent with "one sentence per line" rule, which is very, very helpful for translators :)

Knowing how much difficult this could be to review, I have prepared two commits:
- "double spaces", which could be very easily reviewed by seeing: 
https://github.com/progit/progit2/commit/8d62004d9c300c1461ac90d216c5495adef87a08
or
https://github.com/progit/progit2/commit/8d62004d9c300c1461ac90d216c5495adef87a08?w=1 which uses [?w=1 github feature](https://github.com/blog/967-github-secrets), which ignores whitespaces (that's why commit with that shows as empty)

As far as I know, git or github treats new lines differently, what means that options like `git diff --ignore-*` don't work.

I have prepared special check script: https://gist.github.com/noisy/48e21c8acc8c482b5fe2 to prove, that only newlines were changed.

Just run:

    wget https://gist.githubusercontent.com/noisy/48e21c8acc8c482b5fe2/raw/3180e695b2b0eb46533bcc9d0a754297464b40ab/new-lines-check.py
    python new-lines-check.py

I want to emphasize one fact, that every changed line were examined manually. Script was written in that way, that it proves, that commit contains only changes with new lines.

### CODE REVIEW

**Comment by ben** [comment]
Awesome! Thanks! :smile:

**Comment by YueLinHo** [comment]
> "one sentence per line" rule, which is very, very helpful for translators :)

Could you please point out how it's very helpful? :smiley: Thank you.

**Comment by jnavila** [comment]
I don't know about chinese, but for french, we opted for a sentence by sentence translation. Moreover, later it is easier to follow and apply changes from the original english to the translation. so :+1:

**Comment by YueLinHo** [comment]
> Moreover, later it is easier to follow and apply changes from the original english to the translation.

Yap. I think so, too. :smile: 

Actually, I am going to ask some further questions.

----

Take french repo as example:
* Fetch the french repo. 
* Created `master-fr` which is based on french version. 
* Tried to find out the last sync. with en, and tried to create some tags. (the `fr_fork_point`, `mark_upstream` and `mark_merge_upstream`)

image

So, here is my first further question:

### How to tell easily/quickly the last sync. with en version?

Looks like need to create a branch to point it out.

----

And talking about the method to sync with en.

I tried the `merge` for zh-tw version. 

The red line is en version. 

The black line is zh-tw version, you can see graphic of continuous merges.

image

```
SHA-1: 6dd775d6cf0aee1484937b04395c24aed79009fb
Describe: last_sync-96-g6dd7

Merge commit '627a11026673848b1f122384cd518ec8f9524780' into master-test-merge

Conflicts:
  - book/01-introduction/sections/basics.asc
    commit bb244340865b895fd127f562ee5a60ef3bbcb47c 修正英文文法上的時態，以符合事件發生的順序性。
    同時也修正中文。

Signed-off-by: Yue Lin Ho <b8732003@student.nsysu.edu.tw>
```

When merging, git points out the conflict. Then I confirm the conflict place and decided if the translation is needed to be updated.

I am wondering if this is a good way to go.

So, the second further question is:

### Is there another better way to sync with en version?

**Pull request merged**
