### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by lkord**
MIstake -> PR to trash

### CODE REVIEW

**Comment by ben** [comment]
I think this is mistargeted. This is the repo for the English-language version of the book. Did you mean to make this PR against a different repo?

**Comment by lkord** [comment]
@ben yes, to PL version, I did it also.

**Comment by lkord** [comment]
@ben @jnavila I have pinged him in PR but no contact. I forked repo and started translating, we will see.

**Comment by davpal** [comment]
@lkord I've been granted you write access. I'm pretty busy right now to pay attention on this. It seems like forgotten repo but I started with translations completely alone. Nice to have more contributors ;)

**Comment by lkord** [comment]
@davpal fully understand. Thanks. Cheers

**Pull request closed without merging**
