### PR TITLE
Create section git restore

### LINKED ISSUE #1487: Inconsistency: Git restore is only used once, rest of book uses reset HEAD
**Which version of the book is affected?**

Problem is with the source files, present on current `master`.

**Describe the bug:**

Inconsistency in the way to unstage a staged file.
Our examples use use `git reset HEAD <file to unstage>`.
The status output we show is using `git reset HEAD`, as that is Git's prior advice before the `git restore` command became a thing.

There's one place where the book uses `git restore` and it's introduced with commit: https://github.com/progit/progit2/commit/dc15a308c5ce870699706849a5975dea178cce36

**Steps to reproduce:**

1. Search for hits on the string `git reset HEAD` in the book, notice it's used everywhere for `git status` and unstaging examples the book uses.
2. Search for hits on the string `git restore`, notice it's only used once.

**Expected behavior:**

I expect the book to present a single way to unstage, and be consistent with it, so that readers are never confused.

**Options to fix this:**
1. Revert the merge that resulted in the inconsistency: https://github.com/progit/progit2/pull/1338
2. Revert the merge that resulted in the inconsistency: https://github.com/progit/progit2/pull/1338 plus create a TIP block in an appropriate place in the book with the hint that `git restore` can be used instead of `git reset HEAD`.
3. Change over the entire book to use the newer `git restore` command, and put a note up in a appropriate place with something to the effect of: "If `git restore` doesn't work for you, try `git reset HEAD`.

I'll wait for the maintainers feedback before making a pull request to fix it in one of the three ways listed.

**Context:**

This kind of issue also crops up with: https://github.com/progit/progit2/issues/1441

### PR DESCRIPTION
**Pull request by HonkingGoose**
- [x] I provide my work under the [project license](https://github.com/progit/progit2/blob/master/LICENSE.asc).
- [x] I grant such license of my work as is required for the purposes of future print editions to [Ben Straub](https://github.com/ben) and [Scott Chacon](https://github.com/schacon).

## Changes

- Create section on `git restore`

## Context

Fixes #1487 as we now have a section explaining what `git restore` is.
Read #1487 for the discussion we had leading up to this pull request.

This issue is also related:  #1441 but I'm not closing it with this pull, because that issue also talks about the `git switch` command, which this pull request does not add.

This is a rough draft, that basically copies the two undo sections that used `git reset` and replaced the examples with `git restore`.

I'm of course open to your feedback to improve the text. You always have great suggestions! :smile: :+1: 

---

## Some questions/thoughts:

Should we perhaps change the example a bit more, so that we have less of a deja-vu experience? Or would that confuse readers even more?

I feel what I have now is quite heavy, and duplicates a lot of stuff.

And maybe rewrite this sentence, I really don't like this, it's a bit too complicated to understand at first read:
> The nice part is that the command you use to determine the state of those two areas also reminds you how to undo changes to them.

It's a lot of words to basically say: `git status` is your friend and gives you helpful advice on how to undo stuff. :smile_cat:

### CODE REVIEW

**Comment by HonkingGoose** [comment]
Hi @ben, this is ready for review. It's still a draft, and too rough to merge yet. I'll mark it ready for review after fixing it with your feedback. :smile: :wink:

**Comment by ben** [comment]
Yeah, this looks great!

**Comment by HonkingGoose** [comment]
Changes:

- Squash already approved changes into one commit and rebase on top of current `master`.
- Add warning about `git restore --staged <file>` throwing away your local work.

**Comment by ben** [comment]
:sparkles:

**Pull request merged**
