### PR TITLE
Few changes to the "Distributed Workflow" chapter

### PR DESCRIPTION
**Pull request by sivaraam**
I have made a few changes that I thought would improve the text. It probably might not :). Few other improvement I thought would make the book better are listed below. Please provide suggestions. 

  - There is a line specifying a person named _Tim Pope_ in the _Commit Guidelines_ subsection of the _Contributing to a Project_ section. It would be more clear, if a line about the person was added there.
 -  In the commit template found in the _Commit Guidelines_ subsection of the _Contributing to a Project_ section, there's a line that reads like this, 
> The blank line separating the summary from the body is critical (unless you omit the body entirely); tools like rebase can get confused if you run the two together.

It would be better if the reason, why tools like rebase get confused was stated (concisely, of course). It would help the reader to be more aware of it. (I too don't know why tools get confused and am eager to know the reason :) )

 - There [final illustration](https://github.com/sivaraam/progit2/blob/master/book/05-distributed-git/images/small-team-flow.png) in the _Private Small Team_ of the _Contributing to a Project_ section is good but I guess a `git commit ` arrow is missing in the flow of _Jessica_

### CODE REVIEW

**Comment by ben** [comment]
I like what you've got so far, these are nice touches. Regarding your other points:

1. Rather than explain who Tim Pope is, we should probably just link his name to [the blog post we're referencing](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). I think that's clear enough for the book's purposes, and if people want to know more we've given them a place to start reading.
1. This is just standard etiquette when writing plain text with hard line breaks; two sentences without a blank line between them are treated as though they belong to the same paragraph. This is true for human readers, so lots of people have written their tools to expect this behavior.
1. I'm not sure what you mean by a missing arrow. Jessica's line shows a `git commit` (which creates a commit) and a `git merge` (which also creates a commit). Can you elaborate on what's missing?

**Comment by sivaraam** [comment]
@ben Regarding your responses,
1. That would be a even better choice.
2. Is it possible to add that in some way to the book, like a footnote or something ? It could be informative.
3. If I read the book correctly, I guess the Jessica's flow is missing a git commit before her `git fetch` from the server.

**Comment by sivaraam** [comment]
Few other things I thought would make the book better are listed below, please provide suggestions for them too.

- [ ] A line in the _Forked Public project_ section of the _Contributing to a Project_ section has the following line,

**The reason is that if the work isn’t accepted or is cherry picked, you don’t have to rewind your master branch**

It's the first time the word **cherry picked** is used. Wouldn't it be good to add a line of information about it (or) a pointer to the section which explains it ?

- [ ]  The _Working in Topic Branches_ subsection of the _Maintaining a Project_ section seems to need a little updation. Although it is a section about integrating other people's work it seems to have sentences that relate to contributing work to other people. For example consider the following sentences,

1. **The maintainer of the Git project tends to namespace these branches as well – such as `sc/ruby_client` , where `sc` is short for the person who contributed the work. As you’ll remember, you can create the branch based off your master branch like this,**
           **`$ git branch sc/ruby_client master`**
The above sentence seem a bit confusing as the project which is referred is not so clear, is it a general git project project or the **Git** project itself. Also the intent for including the second sentence is not clear.

2. **Now you’re ready to add your contributed work into this topic branch and determine if you want to merge it into your longer-term branches.**
The above sentence states **your** contributed work, shouldn't that read something like **... add the contributed work...**

- [ ] . In _page 180_ of the PDF version of the book some code seem to extend beyond the code box. This could also be found in _page 181_. This is not an issue in the HTML version of the book.

- [ ]. In the _Applying a patch with am_ subsection of the _Maintaining a Project_ section, the 4th paragraph before the _Checking out Remote Branches_ subsection, the following line seems misleading,

**In this case, this patch had already been applied. Without the -3 option, it looks like a conflict.**

It could be better if it were replaced with something like,

**In this case, without the `-3` option the patch would have been considered as a conflict. Since the `-3` option is used the patch was applied cleanly.**

- [ ]. The below line found under the _Large merging workflows_ sub sub-section of the _Integrating contributed work_ subsection of the _Maintaining a Project section_ is a bit confusing and is barely understandable,

**When it's determined that they're totally stable, the topics are re-merged into `master` and are then rebuilt from the topics that were in `next` but didn't yet graduate to `master`.**

Any suggestions on how to make this more easily understandable ?

**Comment by sivaraam** [comment]
In a code sample, in the same section noted above, found just above Figure 5-17 (second one in page 172 in PDF version of the book), there's a `git fetch origin` command.  I guess the figure 5-17 and the code sample would be better without it. The first command says that `featureB` is based off of `origin/master` but the diagram shows it to be based off of `master` (which is probably  due to the `fetch`) command. There should either be explanation about this or the `git fetch origin` command must be removed from the list of commands and the diagram must be updated.

**Comment by sivaraam** [comment]
The _Working in Topic Branches_ subsection of the _Maintaining a Project_ section seems to need a little updation. Although it is a section about integrating other people's work it seems to have sentences that relate to contributing work to other people. For example consider the following sentences,

1. **The maintainer of the Git project tends to namespace these branches as well – such as `sc/ruby_client` , where `sc` is short for the person who contributed the work. As you’ll remember, you can create the branch based off your master branch like this,**
           **`$ git branch sc/ruby_client master`**
The above sentence seem a bit confusing as the project which is referred is not so clear, is it a general git project project or the **Git** project itself. Also the intent for including the second sentence is not clear.

2. **Now you’re ready to add your contributed work into this topic branch and determine if you want to merge it into your longer-term branches.**
The above sentence states **your** contributed work, shouldn't that read something like **... add the contributed work...**

**Comment by sivaraam** [comment]
Here and there the code samples in the PDF version of the book seem to cross the outline for the code samples A few can be found in the following pages in the PDF version of the book : 172, 180, 181, 192

**Comment by sivaraam** [comment]
- [ ]. In the _Applying a patch with am_ subsection of the _Maintaining a Project_ section, the 4th paragraph before the _Checking out Remote Branches_ subsection, the following line seems misleading,

**In this case, this patch had already been applied. Without the -3 option, it looks like a conflict.**

It could be better if it were replaced with something like,

**In this case, without the `-3` option the patch would have been considered as a conflict. Since the `-3` option is used the patch was applied cleanly.**

**Comment by sivaraam** [comment]
The below line found under the _Large merging workflows_ sub sub-section of the _Integrating contributed work_ subsection of the _Maintaining a Project section_ is a bit confusing and is barely understandable,

**When it's determined that they're totally stable, the topics are re-merged into `master` and are then rebuilt from the topics that were in `next` but didn't yet graduate to `master`.**

Any suggestions on how to make this more easily understandable ?

**Comment by ben** [comment]
Wow. That's a lot of comments and ideas. I'll respond to them here for convenience sake, but let's draw a boundary and move any further changes to other PRs.

> [Linking to Tim Pope] would be a even better choice.

Great. Want to add that to this PR?

> Is it possible to add [an explanation about line-break etiquette] in some way to the book, like a footnote or something ? It could be informative.

Let's make this a separate issue, it warrants a bit of thought.

> If I read the book correctly, I guess the Jessica's flow is missing a git commit before her git fetch from the server.

I see what you're suggesting - a `commit` arrow between the last `merge` and `push` arrows. The [section in question](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Private-Small-Team) has Jessica fetching, merging twice, then pushing. So I guess an extra `merge` arrow would technically be more correct, but the diagram is meant to be conceptual, so I think it's fine how it is.

> It's the first time the word cherry picked is used. Wouldn't it be good to add a line of information about it (or) a pointer to the section which explains it?

There's kind of a chicken-and-egg problem here, but I think we can hand-wave at this particular point in the book. This section doesn't give the exact definition of cherry-pick, but it's clear from context that it means something like "integrating your work into the main project," and that's probably enough for right there.

> In a code sample, in the same section noted above, found just above Figure 5-17 (second one in page 172 in PDF version of the book) […]

Can you link to the online version or the source code?

> The above sentence states your contributed work, shouldn't that read something like ... add the contributed work...

In this context, "you" are the project maintainer, and "your contributed work" refers to the work that has been contributed to your project. I think it works, but if you think it could be better, feel free to submit a change.

> The above sentence seem a bit confusing as the project which is referred is not so clear, is it a general git project project or the Git project itself. Also the intent for including the second sentence is not clear.

Whenever we use the capital-G "Git" form, we're referring to the Git project itself. Again, if you don't feel like this is clear, feel free to try clarifying.

> Here and there the code samples in the PDF version of the book seem to cross the outline for the code samples

Yeah, I see what you mean:

image

Let's open this as a separate issue, it has to do with the PDF toolchain.

> It could be better if it were replaced with something like,

✨ Go ahead and add that change to this PR.

> Any suggestions on how to make this more easily understandable ?

You're asking me, the person who stared at that line for 10 minutes and decided that was the best way to say it? 😉 Feel free to submit a change if you come up with something better, I'd love to see it.

**Comment by sivaraam** [comment]
>I'll respond to them here for convenience sake, but let's draw a boundary and move any further changes to other PRs.

I get that. :)

>Great. Want to add that to this PR?

Yes. Is it ok if I make that line as follows ?

    Here is a http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[template originally written by Tim Pope]:

>Let's make this a separate issue, it warrants a bit of thought.

Sure.

>So I guess an extra merge arrow would technically be more correct, but the diagram is meant to be conceptual, so I think it's fine how it is.

I think it would be better to add that arrow because I love the illustrations in the book and how they easily help me visualise things. So I think keeping the illustrations in sync with the text would be better and would help the reader to easily grasp what he has read. When the reader sees that the illustrations are not in sync with the text he may get confused. (This is the reason I filed #694, but the figure there is really wrong and should be corrected)

>This section doesn't give the exact definition of cherry-pick, but it's clear from context that it means something like "integrating your work into the main project," and that's probably enough for right there.

I thought adding a link to the section would be better because it's done in the book sometimes like the links to _Rewriting History_ that I find often.

>Can you link to the online version or the source code?

The code sample I mentioned starts at `line 565` in the [contributing.asc](https://github.com/progit/progit2/edit/master/book/05-distributed-git/sections/contributing.asc) file. The image I mentioned is the found [here](https://github.com/progit/progit2/blob/master/book/05-distributed-git/images/public-small-1.png).

>Whenever we use the capital-G "Git" form, we're referring to the Git project itself. Again, if you don't feel like this is clear, feel free to try clarifying.

In that case, inspite of changing it in that place wouldn't it be good to add a "little note" at the starting of the book stating this usage so that the reader would be more aware of it ?

>Let's open this as a separate issue, it has to do with the PDF toolchain.

I'll start one for you.

>You're asking me, the person who stared at that line for 10 minutes and decided that was the best way to say it? 😉 Feel free to submit a change if you come up with something better, I'd love to see it.

Sorry, I was a little too expressive there in my comment. What I couldn't get about that line is the second part of it which reads,

**the topics are re-merged into master and are then rebuilt from the topics that were in next but didn’t yet graduate to master .**

I get the point that the topics that are totally stable are merged into `master`. I couldn't get that rebuilding part, could you please clarify that ?

----
I'm ready to push one last change to this pull request after the "link to Mr. Tim Pope's blog" gets correct. I have added one more change that you have specified.

**Comment by sivaraam** [comment]
_Note_ : I have removed the change that fix for #598 for now to keep this PR consistent with it's title :)

**Comment by ben** [comment]
> Yes. Is it ok if I make that line as follows ?

Yup. Commit and push!

> I think it would be better to add that arrow […]

Okay, could you file a separate issue? That way I can close it with a figures-update PR.

> I thought adding a link to the section would be better

Good idea, make it so!

> The code sample I mentioned starts at line 565 […]

Okay, now I see what you're talking about. Actually, I feel like the fetch that's included there is a perfect illustration of how work proceeds in that situation. The upstream `master` branch is always in motion, and you as a contributor are going to have to track it. This gives people an idea of what that looks like. Omitting it would leave potential contributors confused when they actually do have to deal with that.

> In that case, inspite of changing it in that place wouldn't it be good to add a "little note" at the starting of the book stating this usage so that the reader would be more aware of it ?

Yeah, you're right, we don't have a "conventions" section anywhere. We felt like we were sticking to well-known norms for technical books and blog posts, and that a long section that pointed out what it means when a block of text is in monospace was needless. Maybe in this case we could replace the word "Git" with "the Git project"?

> I get the point that the topics that are totally stable are merged into master. I couldn't get that rebuilding part, could you please clarify that ?

The language here isn't super clear because the workflow that this project has adopted is specialized to how the maintainers like to work. To truly understand this, check out [the Git maintainers' guide](https://github.com/git/git/blob/master/Documentation/howto/maintain-git.txt). The biggest things to understand are (a) rebasing happens a lot in that project, (b) `master` is usually fast-forwarded over a series of rebased topic branches, and (c) both `next` and `pu` move around a lot. When you checkout `pu`, you get a view kind of like if all the open PRs on a project were merged at once, and that's different every time `master` moves. "Rebuilding" means regenerating `next` and `pu` after `master` fast-forwards. Does that help?

> Please do forgive me for starting this pull request using my master branch :)

Oh, no worries. Since we're using GitHub for this, it's totally up to you what you name your branches. If you've got multiple PRs going at once it's nice to use something other than `master` (on your side), but it's no inconvenience to me.

**Comment by sivaraam** [comment]
> Okay, could you file a separate issue? That way I can close it with a figures-update PR.

Sure.

> Good idea, make it so!

Ok. I'll add that to another PR.

> Omitting it would leave potential contributors confused when they actually do have to deal with that.

Ok. Then I guess it would be better to add an explanation about that in the book because currently there seems to be no line on the book that says that the `origin/master` branch has moved due to the fetch and hence the some people may think the illustration hasn't matched up with the text. Is it good to add the explanation ?

>Maybe in this case we could replace the word "Git" with "the Git project"?

The sentence is already in the latter form.

>Does that help?
Yes. I guess I understand it now. I'll try to change that line with a more simple on in another PR. I'm not sure if it's correct, so help is needed :)

**Comment by ben** [comment]
> there seems to be no line on the book that says that the origin/master branch has moved due to the fetch

Not in this chapter, no. We cover that in [chapter 3](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches).

**Pull request merged**
