### PR TITLE
Line 229 formatting error by * (asterisk) fixed

### PR DESCRIPTION
**Pull request by max123kl**

### CODE REVIEW

**Comment by ben** [comment]
I see that this fixes a bug in the GitHub renderer, but it looks like the [HTML](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#_ignoring) and [PDF](https://github.com/progit/progit2/releases/download/2.1.164/progit.pdf) versions don't suffer from this bug. Can you verify that this will render correctly in those formats?

**Comment by max123kl** [comment]
I'm sorry, I don't have the experience to do this.

**Comment by tabathap** [comment]
👌

**Comment by yugaego** [comment]
I confirm this PR fixes the issue. See the screenshots below. Tested on the latest master: 14ab61c3b0056a0e5c7f554044f3f04658fcd70e.

Note that wrapping this asterisk into plus signs, as was [suggested by Asciidoctor maintainer](https://github.com/asciidoctor/asciidoctor/issues/3547), also fixes the issue with the same results as shown below.

### On master
*HTML*
before-html

*EPUB*
before-epub

*PDF*
before-pdf


### With the PR fix
*HTML*
after-html

*EPUB*
after-epub

*PDF*
after-pdf

**Comment by ben** [comment]
Lovely, thanks so much, everybody!

**Pull request merged**
