### PR TITLE
SHA-1 of the bottom HEAD is replaced by 68aef35

### PR DESCRIPTION
**Pull request by MaxGekk**
Old SHA-1 (eb43bf8) of HEAD should be replaced by new value (68aef35) as the result of 'git commit'.

### CODE REVIEW

**Comment by ben** [comment]
Sorry for the delay. This looks good, but now there's a conflict. Can you re-apply your change?

**Comment by aollier** [comment]
If you are stuck, this may help you: https://help.github.com/articles/addressing-merge-conflicts/.
You'll be more specifically concerned by this subject since the merge is complex: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/.

**Comment by aizulaiz** [comment]
Update

**Comment by aollier** [comment]
@ben this change is good but very old now. Could you do it by yourself from the most recent commit and close this pull request ?

**Comment by aollier** [comment]
@ben Do you have Sketch 3 to modify the image ? Are you able to do it or not ?
I can't do for my part, because I don't have a MacBook and so I don't have Sketch 3.

**Comment by lazarljubenovic** [comment]
We should really replace these Sketch images with plain old SVGs, to be in spirit of the open source book.

**Comment by parkinson101** [comment]
#1016

**Comment by ninastar78** [comment]
[how-endpoint-encryption-works-en.pdf](https://github.com/progit/progit2/files/2262118/how-endpoint-encryption-works-en.pdf)

**Comment by ninastar78** [comment]
> #1097 
[google-safer-email.zip](https://github.com/progit/progit2/files/2262121/google-safer-email.zip)



-

**Pull request closed without merging**
