### PR TITLE
Rename centralized.png in chapter 5

### LINKED ISSUE #217: Rakefile build uses wrong images with same filename
When building the book via `bundle exec rake book:build`, image files which have the same filename are incorrectly overwritten in the `/images/` directory created by the rake task.

For example, there are two `centralized.png` images, but the `01-introduction/...` one is overwritten by the `05-distributed-git/...` one, which appears in both places in the generated PDF:

```bash
$ find . -name centralized.png
./book/01-introduction/images/centralized.png
./book/05-distributed-git/images/centralized.png
./images/centralized.png <-- this is used in both places in the generated PDF
```

As you can see in the image below, the wrong `centralized.png` is inserted in the introduction chapter.

progit_wrong_image

### PR DESCRIPTION
**Pull request by jnavila**
The name clashes with the chapter 1.

This fixes #217

### CODE REVIEW

**Comment by ben** [comment]
:+1: Thanks!

**Comment by jnavila** [comment]
I couldn't check if this would work. And it seems to have failed... The new picture isn't available..

http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#Centralized-Workflow

**Comment by ben** [comment]
https://github.com/git/git-scm.com/pull/505

**Comment by elbaloo** [comment]
Any updates on this file deployment?

**Pull request merged**
