### PR TITLE
Fix #611

### LINKED ISSUE #611: [Migrate] [SVN] The word "authorization" in msg element
`$ svn log --xml | grep author | sort -u | perl -pe 's/.*>(.*?)<.*/$1 = /'` This command added the messages containing the word "authorization"

I propose
`$ svn log --xml | grep "<author>" | sort -u | perl -pe 's/.*>(.*?)<.*/$1 = /'``

### PR DESCRIPTION
**Pull request by yelmontaser**
#611

### CODE REVIEW

**Comment by ben** [comment]
Looks like you've run into a conflict with #600, which also tried to correct for this. Want to rebase? I think both of the fixes make sense, and shouldn't collide.

**Comment by aizulaiz** [comment]
Update

**Comment by aollier** [comment]
Since @yelmontaser does not answer and #600 seems to solve the problem, I propose to close both this pull request and #611 by mentionning thats #600 resolves it.
@ben Do you agree?

**Comment by ben** [comment]
Sounds good to me. Closing this one and #611.

**Pull request closed without merging**
