### PR TITLE
Update plumbing-porcelain.asc

### PR DESCRIPTION
**Pull request by fabienhinault**
Traduction de la section "Plumbing and porcelain", basée sur la traduction de la version 1 du livre.

### CODE REVIEW

**Comment by ben** [comment]
I *love* that you want to help out, but this doesn't belong here. Take a look at the [French translation repo](https://github.com/progit/progit2-fr) if you'd like to help out with that effort.

**Comment by jnavila** [comment]
Oups... J'ai oublié de te dire...

**Comment by fabienhinault** [comment]
I knew the french translation went to progit2-fr. This was a mixup. Sorry.

**Comment by ben** [comment]
No problem. Thanks for helping out!

**Pull request closed without merging**
