### PR TITLE
resolves #950 - Mislabel in figure 69

### LINKED ISSUE #950: Mislabel in figure 69 - 5.2 Contributing to a Project
Should Josie and John be switched? The features they worked on in the [figure](https://github.com/progit/progit2/blob/master/images/managed-team-flow.png) don't match the main text: "John and Jessica are working together on one feature (call this “featureA”), while Jessica and a third developer, Josie, are working on a second (say, “featureB”)".

### PR DESCRIPTION
**Pull request by yunhailuo**
I'm not good at photo editing. It fixed the name label but doubled the file size.

### CODE REVIEW

**Comment by ben** [comment]
Nice! Maybe run it through https://tinypng.com/ for compression?

**Comment by yunhailuo** [comment]
Thanks @ben ! That works, and I amended the commit. Please check.

**Comment by ben** [comment]
✨

**Comment by YueLinHo** [comment]
This fixed issues #950. Also #449, #694, #1113.
(BTW, the issue #357 is talking about renaming **John/Josie/Jessica** to **Alice/Bob/Candy**.)

Actually, The latest PDF file is good. See:
image

But, [web version](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project) is still wrong:
image

**Comment by ben** [comment]
It's possible there's a job that needs to be run in the website repo to fix this. @peff, do you know what this might be?

**Pull request merged**
