### PR TITLE
Corrected a little typo in a section

### PR DESCRIPTION
**Pull request by sivaraam**
As far as I could think of the word _based_ would fit better than the word _basic_ in that line I changed in the PR. Correct me, if i'm wrong. 

P.S. : Thanks for such a good book on Git

### CODE REVIEW

**Comment by ben** [comment]
Hmm. The term "basic authentication" has a [technical definition](https://tools.ietf.org/html/rfc2617) in the context of HTTP, but I get how that sentence doesn't read particularly well. What if we went with something like this instead:

> […] since you can use things like username/password authentication rather than having to set up SSH keys.

Oh, and you're welcome! I'm glad you like it, thanks for your contribution!

**Comment by sivaraam** [comment]
@ben That would do fine too, sir. I'll make the change.

**Comment by ben** [comment]
✨  Thanks!

**Comment by sivaraam** [comment]
You're welcome!

**Pull request merged**
