### PR TITLE
Expand core.editor command list in Appendix

### PR DESCRIPTION
**Pull request by katrinleinweber**
Following #1269 & #1270, it was suggested to me to include improve the table in these two ways, see commits & diff. Do you think that makes sense?

### CODE REVIEW

**Comment by ben** [comment]
Nice. Thanks!

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Comment by katrinleinweber** [comment]
Ah, oh! I wanted to include https://github.com/progit/progit2/pull/1284 here, but you were too fast :-D

**Comment by ben** [comment]
Whoops! Sometimes I can't tell if a PR is ready for the merge button or not. If you include a checklist and not everything is checked I'll definitely hold off though.

**Pull request merged**
