### PR TITLE
Correct description of Linux kernel maintenance history

### LINKED ISSUE #1675: History of git exaggerates the "patch exchange" portion of the Linux kernel project history
The [*Short History of Git*](https://github.com/progit/progit2/blob/main/book/01-introduction/sections/history.asc) section of Chapter 1 states
> For most of the lifetime of the Linux kernel maintenance (1991–2002), changes to the software were passed around as patches and archived files.

This was certainly true when the first edition of the book was released. It was possibly just barely true when the second edition was published. It has not been true for years. The sentence would be correct if it were reworded to say (for example)
> During the early years of the Linux kernel maintenance (1991-2002), changes to the software ...

### PR DESCRIPTION
**Pull request by bkline**
## Licensing

- [x] I provide my work under the [project license](https://github.com/progit/progit2/blob/main/LICENSE.asc).
- [X] I grant such license of my work as is required for the purposes of future print editions to [Ben Straub](https://github.com/ben) and [Scott Chacon](https://github.com/schacon).

## Changes

- minor tweak to obsolete wording of early history description

Fixes #1675.

### CODE REVIEW

**Review by HonkingGoose — APPROVED** [review]
I like the new wording!

**Comment by JoeandFlora1** [comment]
Thank you for your help. I am excited for a new change already been happening.

**Comment by JoeandFlora1** [comment]
> ## Licensing
> 
> - [x] I provide my work under the [project license](https://github.com/progit/progit2/blob/main/LICENSE.asc).
> - [X] I grant such license of my work as is required for the purposes of future print editions to [Ben Straub](https://github.com/ben) and [Scott Chacon](https://github.com/schacon).
> 
> ## Changes
> 
> - minor tweak to obsolete wording of early history description
> 
> Fixes #1675.
>

**Comment by ben** [comment]
YUS thanks!

**Pull request merged**
