### PR TITLE
Replaced the usage of working directory with working tree in the basi…

### PR DESCRIPTION
**Pull request by vogella**
According to the official Git documentation the term working tree should be used. If this PR gets merged, I'm happy to provide update to the other chapters

See http://git-scm.com/docs/git-read-tree

### CODE REVIEW

**Comment by nobozo** [comment]
I did a quick scan of http://git-scm.com/docs/git-read-tree and I don't see anywhere that says "working tree" should be used instead of "working directory". In fact, that page uses both terms! This looks like an example of Git's inconsistent terminology.

Given all this, plus the amount of work it would take to make this change throughout the whole book, I don't think this change is worthwhile doing.

**Comment by vogella** [comment]
@nobozo maybe a better example is http://git-scm.com/docs/git-clone which only speaks about the working tree. Directory is also used but only to point to the current directory.

I personally think the distinction of "working tree" as checkout of the files and "working directory" as the current working directory is important for the reader. I plan to provide more patches for the other chapters, if this one gets accepted.

**Comment by nobozo** [comment]
I see what you mean, although in the git-clone page "working tree" only appears two times.

However, the more I think about it, the more I like "working tree" because "working directory" implies a single level structure. "Working directory tree" would be even better but I'm not sure anybody would go for that.

In my opinion, the goal for this book, and any other book about Git, should be to use the generally accepted terminology. So, I would recommend getting the opinion of some of the big names in Git, and then using whatever they think is best.

**Comment by vogella** [comment]
@nobozo I send a patch for the Documentation: read-tree to the Git mailing list. I update this PR with the result of their discussion / bashing. :-)

**Comment by vogella** [comment]
@nobozo Also, when I published my Git book based on my online tutorials, +Matthias Sohn project lead for the Eclipse Git project (EGit) and JGit committer project also gave me the feedback that working directory is very confusing for the reader, exact because it implies a flat structure, like you also said.

**Comment by nobozo** [comment]
You've totally convinced me. I'm going to make this change in the "Pro Git Reedited 2nd Ed." book I'm working on (if I ever finish it).

**Comment by vogella** [comment]
Great news. Do you want to use this PR, or shall I abondan it?

**Comment by nobozo** [comment]
I think you should keep it. The book I'm working on is a separate fork of this.

**Comment by vogella** [comment]
FYI My use "working tree instead of working directory" patch got merged into Eclipse Git. http://git.eclipse.org/c/egit/egit.git/commit/?id=e71a75a6311770a6ca14471416832381c61f90f1 … Making the world a better place.

**Comment by ben** [comment]
OK, I'm on board.

**Pull request merged**
