### PR TITLE
Add caution: don't amend pushed commits

### PR DESCRIPTION
**Pull request by HonkingGoose**
- [x] I provide my work under the [project license](https://github.com/progit/progit2/blob/master/LICENSE.asc).
- [x] I grant such license of my work as is required for the purposes of future print editions to [Ben Straub](https://github.com/ben) and [Scott Chacon](https://github.com/schacon).

## Changes

- Add caution block warning readers to be careful when pushing amended commits

## Context

I think we should be more explicit about `git commit --amend` being a good thing for commits that have not been pushed, but potentially problematic for commits that have been pushed already, as that alters the history for everybody who pulls the branch again.

Or do you want me to improve the [NOTE] block that's just above my newly created [CAUTION] block? Maybe having two blocks of warnings is a bit excessive?

### CODE REVIEW

**Comment by ben** [comment]
You know, I actually kind of like the amount of emphasis that comes with backing two "note" type blocks right next to each other. Let's do this.

The only thing I'd suggest is maybe a pointer to the [section](https://github.com/progit/progit2/blob/master/book/03-git-branching/sections/rebasing.asc#the-perils-of-rebasing) where we talk about what happens when you do this, and how to clean it up.

**Comment by HonkingGoose** [comment]
I marked this as a draft for now, until I've made the changes. I'll ping you when it's ready for another round of review. :smile:

**Comment by HonkingGoose** [comment]
Hi @ben, it's ready for another review. :smile: 

## Changes:

- Merge current `master` into pull request
- Change my new `[CAUTION]` block into a `[NOTE]` block.
- Add a link to the "Perils of rebasing" section
- Remove unnecessary comma

**Comment by ben** [comment]
✨

**Pull request merged**
