### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by nunojesus**
I had the Portuguese from Portugal repository.
@jnavila can I continue to do the translations?
Greetings.

### CODE REVIEW

**Comment by 14hooligan88** [comment]
😵

**Comment by aollier** [comment]
Conflict !

**Comment by nunojesus** [comment]
Sorry but I didnt understand the conflict? Can somenone help?

**Comment by lazarljubenovic** [comment]
You've changed a line at some point in the past, say A. Since that point, someone else has also changed that line, in a point in time B (after A). It's now not possible to automatically merge your changes, since that line has been changed. Git refuses to attempt to this on its own because it cannot know for sure what you meant, which is why you have to resolve the conflict yourself.

**Comment by aollier** [comment]
The part you wanted to changed has moved in a new file: TRANSLATING.md.
Update your repository, don't keep your change and report your change in TRANSLATING.md.

**Comment by nunojesus** [comment]
https://github.com/nunojesus/progit2
I create this repository for portuguese translation, and I want to link it to CONTRIBUTING.md

**Comment by aollier** [comment]
You should update your master branch because it is currently 13 commits behind progit:master.
Then merge try to merge your branch in master: you'll see the conflict appear.
Solve it keeping CONTRIBUTING.md unchanged and add your line in TRANSLATING.md.

**Comment by nunojesus** [comment]
So I just have to had my repository link to TRANSLATIONS.md?

**Comment by aollier** [comment]
You can't link a repository to a single file, that has no sense. Do what I told you.

**Comment by aollier** [comment]
This may help you: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging.
Look for "Basic Merge Conflicts".

**Comment by aollier** [comment]
When you will have the conflict solved, do a fast-forward merge on master and push the result.

**Comment by nunojesus** [comment]
Thank you @aollier  for the information, but since Im new on Git, I do not think  I'll be able to do that.  I think I'll contribute to another project.
Thank you again.

**Comment by lazarljubenovic** [comment]
@nunojesus Are you translating the book without trying to read some parts first? Conflicts are explained pretty quickly into the book.

**Comment by aollier** [comment]
@nunojesus Fleeing is not a solution, you'll get this problem at some point, early or late.
You should read Git's manual so you will be able to solve the conflict.

The conflict is that at your point of the history you want to add the line for the portugese translation, but the repository continued to evolve and the part you wanted to modify was moved ino a new file: TRANSLATING.md.
The only thing you have to do is to report your change in TRANSLATING.md.
I explained to you how to do. Read Git's manual to see what the process is.

**Comment by jnavila** [comment]
@aollier @lazarljubenovic If you look at the information besides the commit you'll see that there is this small 
image

This means that the file was edited directly on the GitHub Website. Lately, we had a lot of people coming from utopian.io and trying to contribute on GitHub, but without any knowledge in Git itself.

GitHub makes it quite simple to start editing and creating pull requests by just opening a file of a project in the GitHub web interface, pressing the pencil button and starting editing in the browser. This is a curse for us because, although that should bring us new contributors, these ones are not educated enough on Git to be really able to interact with the repository. Moreover, coming from Utopian.io, they don't want to spend time learning Git (to difficult, not for me,...)

@nunojesus I can make the inclusion of pt-pt in the list by myself. But, really, it seems you are in software industry and Git would be a huge improvement for your work also.

**Comment by nunojesus** [comment]
Hello @jnavila l, as you say I have been contributing in projects through utopian.io, I am new to Git and I intend to learn in the present and in the future, because without any doubt that is an excellent tool. I am a civil engineer and in my free time I do some designer work and lately I have done translation work for open source projects and I love it. So it is very difficult for me at this moment to have time to learn Git, but I will do it surely. I already have Git installed on my computer which is already a principle. If you want to include the pt-pt in the list would be great for me, otherwise I will do it later, when I have obtained knowledge for such. Thank you very much.

**Comment by wilegithub** [comment]
Subscribe

**Pull request closed without merging**
