### PR TITLE
No package getopt on debian

### PR DESCRIPTION
**Pull request by Pherserk**
No package getopt on debian: https://packages.debian.org/search?suite=jessie&arch=i386&mode=filename&searchon=contents&keywords=getopt

### CODE REVIEW

**Comment by ben** [comment]
Can you confirm that this new command line will make it so you can build the Git documentation from source?

**Comment by jnavila** [comment]
On my Debian Testing system, there's no `gnulib` package installed. `/usr/include/getopt.h` is coming from the package `libc6-dev`.

**Comment by ben** [comment]
@Pherserk, we're coming up on 9 months since you submitted this. Any chance you can confirm that it works?

**Comment by jnavila** [comment]
`gnulib` is a subset of libc for embedded systems, I'm pretty sure that this isn't needed. OTOH, `libc6-dev` is installed as a dependency of `build-essential` which should be listed.

**Comment by ben** [comment]
Well, it looks like the source fork for this PR is gone. I'm going to close this out for now, let's see if anyone else runs up against this.

**Pull request closed without merging**
