### PR TITLE
Major rewrite of TRANSLATING.md

### PR DESCRIPTION
**Pull request by HonkingGoose**
Hi @ben,

I took the liberty of starting a major rewrite of TRANSLATING.md

### Main changes:
1. Changed table to proper GitHub Flavoured Markdown format. (I had problems getting the table to behave after my edits, so I rewrote it in proper GFM).
1. Added new table with the three stages a translation can be in.
1. Rewrite of the Travis CI sections.
1. Removal of Beyond Git (I don't think a section on hacking on git should be in a file about translating.)
1. General cleanup of text.

### Minor changes:
1. Changed some header text.
1. Changed header level.

### Feedback wanted on:

Maybe the Travis section can be made clearer? Maybe you have some suggestions on this? You use the system daily I think... :smile: 

And of-course I would like some feedback on the style/content of this rewrite.

### CODE REVIEW

**Comment by ben** [comment]
It looks good to me. Let's see if any prospective translators have issues with it.

**Comment by jnavila** [comment]
I don't quite catch why you think the "Beyond Progit" section is not pertinent. When translating Progit, you get a knowledge of Git itself. It is the perfect start for translating the strings in the tool itself. It's not about hacking Git, it's just about extending the translations, and having the same teams having a look at how things are translated on other aspects of Git. Please not also that I started a project to translate manpages. I guess these two translation projects deserve at least a mention in this document.

**Comment by HonkingGoose** [comment]
@jnavila I'm sorry, I misunderstood the text, I was under the impression that that section was about hacking on git itself, instead of making translations for the git technical documentation. I've made a new pull-request to revert that change. You can see it at: #1230

The project to translate manpages is not yet mentioned in translating.md so you can write a section on that if you like and make a new pull-request to pull it in. :+1:

**Comment by jnavila** [comment]
Anyway, thanks for rewriting this section. It's a lot clearer now.

**Pull request merged**
