### PR TITLE
Undoing things: Clarify what "git checkout" does to local files

### PR DESCRIPTION
**Pull request by rpjday**
The current explanation of "git checkout -- <file>" seems a bit
vague, so expand on it ever so slightly.

Signed-off-by: Robert P. J. Day <rpjday@crashcourse.ca>

### CODE REVIEW

**Comment by ben** [comment]
Nice, thanks!

**Comment by bripmccann** [comment]
Maybe I'm being unnecessarily picky, because the meaning is clear, but '<i>over top of</i>' sounds odd to me. Certainly '<i>**on** top of</i>' is the more common idiom—but in the case of copying, the old wording, ['<i>copy over</i>', seems to be the most common](https://trends.google.com/trends/explore?q=copy%20over,copy%20over%20top,copy%20on%20top).

But like I said, the meaning is still clear. I don't find '<i>copy over</i>' vague, but if it does add clarity for others I'd say it's worth a little awkwardness.

(P.S. I don't know if people usually comment on pull requests after they're merged? My bad if I should've opened an issue or something.)

**Comment by ben** [comment]
I'd agree that it isn't that common, and it definitely feels a bit odd to me saying it out loud, but it does get the point across, and I don't think anybody will misread that passage to mean something else.

Do you want to submit a PR so we can see what it looks like?

**Comment by HonkingGoose** [comment]
Hi @ben, you've merged PR #1246, doesn't that close this issue? Or is there more work to be done here still?

**Comment by aollier** [comment]
@HonkingGoose Which issue are you talking about?

**Comment by HonkingGoose** [comment]
Hi @aollier,

- This issue was first about: https://github.com/progit/progit2/pull/1179#issue-253463012
- And then about: https://github.com/progit/progit2/pull/1179#issuecomment-468422175

It seems that both those things are now fixed, so this issue (#1179) can be closed?

**Comment by aollier** [comment]
@HonkingGoose Good.
Reminder: if you add a new commit or open a new pull request in order to close an issue, the recommended way of doing it is by [closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords).

Furthermore, if you work on Windows and are using TortoiseGit, you can see the issue related to the commit if the commit contains one of the keywords followed by # followed by the issue ID thanks to #1127.

**Comment by bripmccann** [comment]
My commit message for PR #1246 was ambiguous. You'd usually be right to assume I was referencing an issue, not a different pull request. I've edited the commit message to clarify.

**Pull request merged**
