### PR TITLE
Fix issue #541: Add TortoiseGit config for bugtraq and icon

### PR DESCRIPTION
**Pull request by YueLinHo**
### Before

image

### After

image

### Before

image

### After

image (Updated as @ben wish.)

cf. [TortioseGit Settings Doc](https://tortoisegit.org/docs/tortoisegit/tgit-dug-settings.html) - the **Overlay Icon** section.

### CODE REVIEW

**Comment by ben** [comment]
Hmm. Should we use the cover for this edition instead?

**Comment by YueLinHo** [comment]
> Should we use the cover for this edition instead?

Yes.

Is this good enough?

image

or this?

image

or give me the font name of "Pro Git", I design another icon?

**Comment by ben** [comment]
I like the top one the best, I think.

**Comment by YueLinHo** [comment]
Updated the PR.

**Comment by YueLinHo** [comment]
Thanks @ben. ^____^

**Comment by YueLinHo** [comment]
Fixed #541

**Pull request merged**
