### PR TITLE
fixed number error in transfer-protocols example

### PR DESCRIPTION
**Pull request by zwpaper**
I found the best way to fix the error is correcting the numbers, so I did it.

### CODE REVIEW

**Comment by zwpaper** [comment]
I delete a space and a line, I made a commit each line, review it please.

**Comment by ben** [comment]
Apart from including the `□` character, this looks great!

**Comment by zwpaper** [comment]
added a □ to indicate the '0x00', and happened to find another two mistaken. review it please.

BTW, is the order of '00009done' and '0000' in line 251 and 252 right?
In my opinion, the '0000' should be the end of a message, but here it shows up before the '0009done'.
I have try to catch the package, but the package is encrypted.
and in line 280, there is no '0009done', should it be like this?

excuse me for that I find nothing for the answer to this question, so that I have to ask here.

**Comment by zwpaper** [comment]
@ben I have find the answer in the source code of git, it should be 
```
0009done
0000
```
I will update the PR, and the sample should be finally correct!

**Comment by ben** [comment]
Beautiful. Thanks!

**Pull request merged**
