### PR TITLE
Filipino / Tagalog Translations

### PR DESCRIPTION
**Pull request by severinolorillajr**
I have completed the Filipino translations for the whole first chapter of the book.
Hope that you can check this out. If there are some things that I need to comply first before we can merge this, you can contact me anytime through this PR or directly to my email at severinolorillajr@gmail.com.

I am very eager to continue with the rest of the chapters, so I'm really looking forward for your feedback.

### CODE REVIEW

**Comment by jnavila** [comment]
Hi Severino,

That's good to see a new language pop up in the translations! Translations are managed in their own repositories so opening a PR here is useless as this repo will only manage the English original version.

To open a new language, all you need is follow the directions written in 
https://github.com/progit/progit2/blob/master/CONTRIBUTING.md

**Comment by severinolorillajr** [comment]
I have already read the guide you pasted above.
In fact I already have this 
https://github.com/progit2-tl/progit2
What's the next step?

**Comment by jnavila** [comment]
Good! Then, there are remaining steps:

 * add an entry in this repo in CONTRIBUTING.md for your language (Add your language in its own form)
 * Make the necessary changes in git-scm.com website to add your language (I can do it once I know how to write your language name)
 * Optionaly, set up the automatic compilation of ebook and pdf via a script for travis-ci (not documented yet but I can help)

**Comment by severinolorillajr** [comment]
Made a new PR for CONTRIBUTING.md updates.
I guess I need help with the last 2 items.

**Comment by severinolorillajr** [comment]
Closing this pr as this no longer needed. Thank you.

**Pull request closed without merging**
