### PR TITLE
removed unused images

### PR DESCRIPTION
**Pull request by aollier**
Those images are no more used since a while:

```bash
$ git log -S'gitlab-broadcast.png' -1 --name-only
commit 9b73763f083c115eac9827837e81e89e6f48d098
Author: Ben Straub <ben@straub.cc>
Date:   Sun Mar 23 09:16:49 2014 -0700

    Trim and focus for GitLab content

en/book/04-git-server/chapter4.asc
# no longer used since this commit
$ git log -S'merging-workflows-4 2.png' --max-count=1 --name-only
# no result, never used
$ git log -S'blink-pull-request-open copy.png' --max-count=1 --name-only
# no result, never used
$ git log -S'blink-pull-request-open.png' --max-count=1 --name-only
commit 6b0acf02212703b98bb88adf0c47f7b55a336b18
Author: Scott Chacon <schacon@gmail.com>
Date:   Wed Oct 1 13:20:58 2014 +0200

    partially done with 6.2

book/06-github/sections/github-flow.asc
# no longer used since this commit
$ git log -Shubot.png --max-count=1 --name-only
commit 6b0acf02212703b98bb88adf0c47f7b55a336b18
Author: Scott Chacon <schacon@gmail.com>
Date:   Wed Oct 1 13:20:58 2014 +0200

    partially done with 6.2

book/06-github/sections/projects.asc
# no longer used since this commit
```
Every other images are still used.

### CODE REVIEW

**Comment by ben** [comment]
👍🏼 thanks for doing this! I notice you're removing an image of Hubot too, did you run the log to check that one as well?

**Comment by aollier** [comment]
Yes I did, it is the second to last:
```
$ git log -Shubot.png --max-count=1 --name-only
commit 6b0acf02212703b98bb88adf0c47f7b55a336b18
Author: Scott Chacon <schacon@gmail.com>
Date:   Wed Oct 1 13:20:58 2014 +0200

    partially done with 6.2

book/06-github/sections/projects.asc
# no longer used since this commit
```
The file `book/06-github/sections/projects.asc` was removed at commit 6b0acf0, so the last reference to book/06-github/images/hubot.png too.

**Comment by aollier** [comment]
You can check that there is no more reference to hubot.png by running this command:
```bash
git grep --fixed-strings --files-with-matches 'hubot.png' \*.asc
```
This command returns no result.

**Comment by ben** [comment]
Aha, I see it now. Sorry, hadn't had my coffee yet. Thanks!

**Pull request merged**
